pipeline {
    agent any

    stages {

        stage('Install Dependencies') {
            steps {
                withEnv(["PATH+FLUTTER=/opt/homebrew/bin:/Users/debayo_egov/tools/flutter/bin"]) {
                    dir('inspektoor_flutter') {
                        sh 'flutter pub get'
                    }
                }
            }
        }

        stage('Analyze') {
            steps {
                withEnv(["PATH+FLUTTER=/opt/homebrew/bin:/Users/debayo_egov/tools/flutter/bin"]) {
                    dir('inspektoor_flutter') {
                        sh 'flutter analyze'
                    }
                }
            }
        }

        stage('Test') {
            steps {
                withEnv(["PATH+FLUTTER=/opt/homebrew/bin:/Users/debayo_egov/tools/flutter/bin"]) {
                    dir('inspektoor_flutter') {
                        sh 'flutter test'
                    }
                }
            }
        }

        stage('Build Android') {
            steps {
                withEnv(["PATH+FLUTTER=/opt/homebrew/bin:/Users/debayo_egov/tools/flutter/bin"]) {
                    dir('inspektoor_flutter') {
                        sh 'flutter build appbundle --release'
                    }
                }
            }
        }

        stage('Build iOS') {
            steps {
                withEnv(["PATH+FLUTTER=/opt/homebrew/bin:/Users/debayo_egov/tools/flutter/bin"]) {
                    dir('inspektoor_flutter') {
                        sh 'flutter build ios --release --no-codesign'
                    }
                }
            }
        }

    }

    post {
        success {
            echo '✅ Build succeeded!'
        }
        failure {
            echo '❌ Build failed!'
        }
    }
}